/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZededaList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZededaList{}

// ZededaList struct for ZededaList
type ZededaList struct {
	Data []ZededaListDto `json:"data"`
	TotalCount int32 `json:"totalCount"`
}

type _ZededaList ZededaList

// NewZededaList instantiates a new ZededaList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZededaList(data []ZededaListDto, totalCount int32) *ZededaList {
	this := ZededaList{}
	this.Data = data
	this.TotalCount = totalCount
	return &this
}

// NewZededaListWithDefaults instantiates a new ZededaList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZededaListWithDefaults() *ZededaList {
	this := ZededaList{}
	return &this
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for []ZededaListDto will be returned
func (o *ZededaList) GetData() []ZededaListDto {
	if o == nil {
		var ret []ZededaListDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ZededaList) GetDataOk() ([]ZededaListDto, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ZededaList) SetData(v []ZededaListDto) {
	o.Data = v
}

// GetTotalCount returns the TotalCount field value
func (o *ZededaList) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ZededaList) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ZededaList) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o ZededaList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZededaList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

func (o *ZededaList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZededaList := _ZededaList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZededaList)

	if err != nil {
		return err
	}

	*o = ZededaList(varZededaList)

	return err
}

type NullableZededaList struct {
	value *ZededaList
	isSet bool
}

func (v NullableZededaList) Get() *ZededaList {
	return v.value
}

func (v *NullableZededaList) Set(val *ZededaList) {
	v.value = val
	v.isSet = true
}

func (v NullableZededaList) IsSet() bool {
	return v.isSet
}

func (v *NullableZededaList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZededaList(val *ZededaList) *NullableZededaList {
	return &NullableZededaList{value: val, isSet: true}
}

func (v NullableZededaList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZededaList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


