/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: 1.0.0
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectAppDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAppDto{}

// ProjectAppDto struct for ProjectAppDto
type ProjectAppDto struct {
	Id int32 `json:"id"`
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	ProjectName *string `json:"projectName,omitempty"`
	ProjectId int32 `json:"projectId"`
	Version *string `json:"version,omitempty"`
	IsLocked bool `json:"isLocked"`
	Status EInstanceStatus `json:"status"`
	AutoSync bool `json:"autoSync"`
}

type _ProjectAppDto ProjectAppDto

// NewProjectAppDto instantiates a new ProjectAppDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAppDto(id int32, projectId int32, isLocked bool, status EInstanceStatus, autoSync bool) *ProjectAppDto {
	this := ProjectAppDto{}
	this.Id = id
	this.ProjectId = projectId
	this.IsLocked = isLocked
	this.Status = status
	this.AutoSync = autoSync
	return &this
}

// NewProjectAppDtoWithDefaults instantiates a new ProjectAppDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAppDtoWithDefaults() *ProjectAppDto {
	this := ProjectAppDto{}
	return &this
}

// GetId returns the Id field value
func (o *ProjectAppDto) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectAppDto) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectAppDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectAppDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectAppDto) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ProjectAppDto) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ProjectAppDto) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ProjectAppDto) SetNamespace(v string) {
	o.Namespace = &v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *ProjectAppDto) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *ProjectAppDto) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *ProjectAppDto) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectAppDto) GetProjectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetProjectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectAppDto) SetProjectId(v int32) {
	o.ProjectId = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ProjectAppDto) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ProjectAppDto) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ProjectAppDto) SetVersion(v string) {
	o.Version = &v
}

// GetIsLocked returns the IsLocked field value
func (o *ProjectAppDto) GetIsLocked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLocked
}

// GetIsLockedOk returns a tuple with the IsLocked field value
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetIsLockedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLocked, true
}

// SetIsLocked sets field value
func (o *ProjectAppDto) SetIsLocked(v bool) {
	o.IsLocked = v
}

// GetStatus returns the Status field value
func (o *ProjectAppDto) GetStatus() EInstanceStatus {
	if o == nil {
		var ret EInstanceStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetStatusOk() (*EInstanceStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectAppDto) SetStatus(v EInstanceStatus) {
	o.Status = v
}

// GetAutoSync returns the AutoSync field value
func (o *ProjectAppDto) GetAutoSync() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AutoSync
}

// GetAutoSyncOk returns a tuple with the AutoSync field value
// and a boolean to check if the value has been set.
func (o *ProjectAppDto) GetAutoSyncOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AutoSync, true
}

// SetAutoSync sets field value
func (o *ProjectAppDto) SetAutoSync(v bool) {
	o.AutoSync = v
}

func (o ProjectAppDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAppDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	toSerialize["projectId"] = o.ProjectId
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	toSerialize["isLocked"] = o.IsLocked
	toSerialize["status"] = o.Status
	toSerialize["autoSync"] = o.AutoSync
	return toSerialize, nil
}

func (o *ProjectAppDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"projectId",
		"isLocked",
		"status",
		"autoSync",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectAppDto := _ProjectAppDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectAppDto)

	if err != nil {
		return err
	}

	*o = ProjectAppDto(varProjectAppDto)

	return err
}

type NullableProjectAppDto struct {
	value *ProjectAppDto
	isSet bool
}

func (v NullableProjectAppDto) Get() *ProjectAppDto {
	return v.value
}

func (v *NullableProjectAppDto) Set(val *ProjectAppDto) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAppDto) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAppDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAppDto(val *ProjectAppDto) *NullableProjectAppDto {
	return &NullableProjectAppDto{value: val, isSet: true}
}

func (v NullableProjectAppDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAppDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


