/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: 1.0.0
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the TrustedRegisteredCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrustedRegisteredCreateDto{}

// TrustedRegisteredCreateDto struct for TrustedRegisteredCreateDto
type TrustedRegisteredCreateDto struct {
	Registry *string `json:"registry,omitempty"`
}

// NewTrustedRegisteredCreateDto instantiates a new TrustedRegisteredCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrustedRegisteredCreateDto() *TrustedRegisteredCreateDto {
	this := TrustedRegisteredCreateDto{}
	return &this
}

// NewTrustedRegisteredCreateDtoWithDefaults instantiates a new TrustedRegisteredCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrustedRegisteredCreateDtoWithDefaults() *TrustedRegisteredCreateDto {
	this := TrustedRegisteredCreateDto{}
	return &this
}

// GetRegistry returns the Registry field value if set, zero value otherwise.
func (o *TrustedRegisteredCreateDto) GetRegistry() string {
	if o == nil || IsNil(o.Registry) {
		var ret string
		return ret
	}
	return *o.Registry
}

// GetRegistryOk returns a tuple with the Registry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrustedRegisteredCreateDto) GetRegistryOk() (*string, bool) {
	if o == nil || IsNil(o.Registry) {
		return nil, false
	}
	return o.Registry, true
}

// HasRegistry returns a boolean if a field has been set.
func (o *TrustedRegisteredCreateDto) HasRegistry() bool {
	if o != nil && !IsNil(o.Registry) {
		return true
	}

	return false
}

// SetRegistry gets a reference to the given string and assigns it to the Registry field.
func (o *TrustedRegisteredCreateDto) SetRegistry(v string) {
	o.Registry = &v
}

func (o TrustedRegisteredCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrustedRegisteredCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Registry) {
		toSerialize["registry"] = o.Registry
	}
	return toSerialize, nil
}

type NullableTrustedRegisteredCreateDto struct {
	value *TrustedRegisteredCreateDto
	isSet bool
}

func (v NullableTrustedRegisteredCreateDto) Get() *TrustedRegisteredCreateDto {
	return v.value
}

func (v *NullableTrustedRegisteredCreateDto) Set(val *TrustedRegisteredCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTrustedRegisteredCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTrustedRegisteredCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrustedRegisteredCreateDto(val *TrustedRegisteredCreateDto) *NullableTrustedRegisteredCreateDto {
	return &NullableTrustedRegisteredCreateDto{value: val, isSet: true}
}

func (v NullableTrustedRegisteredCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrustedRegisteredCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


