/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the VirtualClusterResourceQuotas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VirtualClusterResourceQuotas{}

// VirtualClusterResourceQuotas struct for VirtualClusterResourceQuotas
type VirtualClusterResourceQuotas struct {
	Pods *int32 `json:"pods,omitempty"`
	CpuRequests *float64 `json:"cpuRequests,omitempty"`
	CpuLimits *float64 `json:"cpuLimits,omitempty"`
	RamRequests *int64 `json:"ramRequests,omitempty"`
	RamLimits *int64 `json:"ramLimits,omitempty"`
	Pvcs *int32 `json:"pvcs,omitempty"`
	TotalPvcSize *int64 `json:"totalPvcSize,omitempty"`
	Ingresses *int32 `json:"ingresses,omitempty"`
	LoadBalancers *int32 `json:"loadBalancers,omitempty"`
}

// NewVirtualClusterResourceQuotas instantiates a new VirtualClusterResourceQuotas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualClusterResourceQuotas() *VirtualClusterResourceQuotas {
	this := VirtualClusterResourceQuotas{}
	return &this
}

// NewVirtualClusterResourceQuotasWithDefaults instantiates a new VirtualClusterResourceQuotas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualClusterResourceQuotasWithDefaults() *VirtualClusterResourceQuotas {
	this := VirtualClusterResourceQuotas{}
	return &this
}

// GetPods returns the Pods field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetPods() int32 {
	if o == nil || IsNil(o.Pods) {
		var ret int32
		return ret
	}
	return *o.Pods
}

// GetPodsOk returns a tuple with the Pods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetPodsOk() (*int32, bool) {
	if o == nil || IsNil(o.Pods) {
		return nil, false
	}
	return o.Pods, true
}

// HasPods returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasPods() bool {
	if o != nil && !IsNil(o.Pods) {
		return true
	}

	return false
}

// SetPods gets a reference to the given int32 and assigns it to the Pods field.
func (o *VirtualClusterResourceQuotas) SetPods(v int32) {
	o.Pods = &v
}

// GetCpuRequests returns the CpuRequests field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetCpuRequests() float64 {
	if o == nil || IsNil(o.CpuRequests) {
		var ret float64
		return ret
	}
	return *o.CpuRequests
}

// GetCpuRequestsOk returns a tuple with the CpuRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetCpuRequestsOk() (*float64, bool) {
	if o == nil || IsNil(o.CpuRequests) {
		return nil, false
	}
	return o.CpuRequests, true
}

// HasCpuRequests returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasCpuRequests() bool {
	if o != nil && !IsNil(o.CpuRequests) {
		return true
	}

	return false
}

// SetCpuRequests gets a reference to the given float64 and assigns it to the CpuRequests field.
func (o *VirtualClusterResourceQuotas) SetCpuRequests(v float64) {
	o.CpuRequests = &v
}

// GetCpuLimits returns the CpuLimits field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetCpuLimits() float64 {
	if o == nil || IsNil(o.CpuLimits) {
		var ret float64
		return ret
	}
	return *o.CpuLimits
}

// GetCpuLimitsOk returns a tuple with the CpuLimits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetCpuLimitsOk() (*float64, bool) {
	if o == nil || IsNil(o.CpuLimits) {
		return nil, false
	}
	return o.CpuLimits, true
}

// HasCpuLimits returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasCpuLimits() bool {
	if o != nil && !IsNil(o.CpuLimits) {
		return true
	}

	return false
}

// SetCpuLimits gets a reference to the given float64 and assigns it to the CpuLimits field.
func (o *VirtualClusterResourceQuotas) SetCpuLimits(v float64) {
	o.CpuLimits = &v
}

// GetRamRequests returns the RamRequests field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetRamRequests() int64 {
	if o == nil || IsNil(o.RamRequests) {
		var ret int64
		return ret
	}
	return *o.RamRequests
}

// GetRamRequestsOk returns a tuple with the RamRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetRamRequestsOk() (*int64, bool) {
	if o == nil || IsNil(o.RamRequests) {
		return nil, false
	}
	return o.RamRequests, true
}

// HasRamRequests returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasRamRequests() bool {
	if o != nil && !IsNil(o.RamRequests) {
		return true
	}

	return false
}

// SetRamRequests gets a reference to the given int64 and assigns it to the RamRequests field.
func (o *VirtualClusterResourceQuotas) SetRamRequests(v int64) {
	o.RamRequests = &v
}

// GetRamLimits returns the RamLimits field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetRamLimits() int64 {
	if o == nil || IsNil(o.RamLimits) {
		var ret int64
		return ret
	}
	return *o.RamLimits
}

// GetRamLimitsOk returns a tuple with the RamLimits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetRamLimitsOk() (*int64, bool) {
	if o == nil || IsNil(o.RamLimits) {
		return nil, false
	}
	return o.RamLimits, true
}

// HasRamLimits returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasRamLimits() bool {
	if o != nil && !IsNil(o.RamLimits) {
		return true
	}

	return false
}

// SetRamLimits gets a reference to the given int64 and assigns it to the RamLimits field.
func (o *VirtualClusterResourceQuotas) SetRamLimits(v int64) {
	o.RamLimits = &v
}

// GetPvcs returns the Pvcs field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetPvcs() int32 {
	if o == nil || IsNil(o.Pvcs) {
		var ret int32
		return ret
	}
	return *o.Pvcs
}

// GetPvcsOk returns a tuple with the Pvcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetPvcsOk() (*int32, bool) {
	if o == nil || IsNil(o.Pvcs) {
		return nil, false
	}
	return o.Pvcs, true
}

// HasPvcs returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasPvcs() bool {
	if o != nil && !IsNil(o.Pvcs) {
		return true
	}

	return false
}

// SetPvcs gets a reference to the given int32 and assigns it to the Pvcs field.
func (o *VirtualClusterResourceQuotas) SetPvcs(v int32) {
	o.Pvcs = &v
}

// GetTotalPvcSize returns the TotalPvcSize field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetTotalPvcSize() int64 {
	if o == nil || IsNil(o.TotalPvcSize) {
		var ret int64
		return ret
	}
	return *o.TotalPvcSize
}

// GetTotalPvcSizeOk returns a tuple with the TotalPvcSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetTotalPvcSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalPvcSize) {
		return nil, false
	}
	return o.TotalPvcSize, true
}

// HasTotalPvcSize returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasTotalPvcSize() bool {
	if o != nil && !IsNil(o.TotalPvcSize) {
		return true
	}

	return false
}

// SetTotalPvcSize gets a reference to the given int64 and assigns it to the TotalPvcSize field.
func (o *VirtualClusterResourceQuotas) SetTotalPvcSize(v int64) {
	o.TotalPvcSize = &v
}

// GetIngresses returns the Ingresses field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetIngresses() int32 {
	if o == nil || IsNil(o.Ingresses) {
		var ret int32
		return ret
	}
	return *o.Ingresses
}

// GetIngressesOk returns a tuple with the Ingresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetIngressesOk() (*int32, bool) {
	if o == nil || IsNil(o.Ingresses) {
		return nil, false
	}
	return o.Ingresses, true
}

// HasIngresses returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasIngresses() bool {
	if o != nil && !IsNil(o.Ingresses) {
		return true
	}

	return false
}

// SetIngresses gets a reference to the given int32 and assigns it to the Ingresses field.
func (o *VirtualClusterResourceQuotas) SetIngresses(v int32) {
	o.Ingresses = &v
}

// GetLoadBalancers returns the LoadBalancers field value if set, zero value otherwise.
func (o *VirtualClusterResourceQuotas) GetLoadBalancers() int32 {
	if o == nil || IsNil(o.LoadBalancers) {
		var ret int32
		return ret
	}
	return *o.LoadBalancers
}

// GetLoadBalancersOk returns a tuple with the LoadBalancers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualClusterResourceQuotas) GetLoadBalancersOk() (*int32, bool) {
	if o == nil || IsNil(o.LoadBalancers) {
		return nil, false
	}
	return o.LoadBalancers, true
}

// HasLoadBalancers returns a boolean if a field has been set.
func (o *VirtualClusterResourceQuotas) HasLoadBalancers() bool {
	if o != nil && !IsNil(o.LoadBalancers) {
		return true
	}

	return false
}

// SetLoadBalancers gets a reference to the given int32 and assigns it to the LoadBalancers field.
func (o *VirtualClusterResourceQuotas) SetLoadBalancers(v int32) {
	o.LoadBalancers = &v
}

func (o VirtualClusterResourceQuotas) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VirtualClusterResourceQuotas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pods) {
		toSerialize["pods"] = o.Pods
	}
	if !IsNil(o.CpuRequests) {
		toSerialize["cpuRequests"] = o.CpuRequests
	}
	if !IsNil(o.CpuLimits) {
		toSerialize["cpuLimits"] = o.CpuLimits
	}
	if !IsNil(o.RamRequests) {
		toSerialize["ramRequests"] = o.RamRequests
	}
	if !IsNil(o.RamLimits) {
		toSerialize["ramLimits"] = o.RamLimits
	}
	if !IsNil(o.Pvcs) {
		toSerialize["pvcs"] = o.Pvcs
	}
	if !IsNil(o.TotalPvcSize) {
		toSerialize["totalPvcSize"] = o.TotalPvcSize
	}
	if !IsNil(o.Ingresses) {
		toSerialize["ingresses"] = o.Ingresses
	}
	if !IsNil(o.LoadBalancers) {
		toSerialize["loadBalancers"] = o.LoadBalancers
	}
	return toSerialize, nil
}

type NullableVirtualClusterResourceQuotas struct {
	value *VirtualClusterResourceQuotas
	isSet bool
}

func (v NullableVirtualClusterResourceQuotas) Get() *VirtualClusterResourceQuotas {
	return v.value
}

func (v *NullableVirtualClusterResourceQuotas) Set(val *VirtualClusterResourceQuotas) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualClusterResourceQuotas) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualClusterResourceQuotas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualClusterResourceQuotas(val *VirtualClusterResourceQuotas) *NullableVirtualClusterResourceQuotas {
	return &NullableVirtualClusterResourceQuotas{value: val, isSet: true}
}

func (v NullableVirtualClusterResourceQuotas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualClusterResourceQuotas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


