/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the DeletePrometheusRulesFromOrganizationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePrometheusRulesFromOrganizationDto{}

// DeletePrometheusRulesFromOrganizationDto struct for DeletePrometheusRulesFromOrganizationDto
type DeletePrometheusRulesFromOrganizationDto struct {
	Id *int32 `json:"id,omitempty"`
	DiscountRate NullableFloat64 `json:"discountRate,omitempty"`
	IsBound *bool `json:"isBound,omitempty"`
}

// NewDeletePrometheusRulesFromOrganizationDto instantiates a new DeletePrometheusRulesFromOrganizationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePrometheusRulesFromOrganizationDto() *DeletePrometheusRulesFromOrganizationDto {
	this := DeletePrometheusRulesFromOrganizationDto{}
	return &this
}

// NewDeletePrometheusRulesFromOrganizationDtoWithDefaults instantiates a new DeletePrometheusRulesFromOrganizationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePrometheusRulesFromOrganizationDtoWithDefaults() *DeletePrometheusRulesFromOrganizationDto {
	this := DeletePrometheusRulesFromOrganizationDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeletePrometheusRulesFromOrganizationDto) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePrometheusRulesFromOrganizationDto) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeletePrometheusRulesFromOrganizationDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DeletePrometheusRulesFromOrganizationDto) SetId(v int32) {
	o.Id = &v
}

// GetDiscountRate returns the DiscountRate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeletePrometheusRulesFromOrganizationDto) GetDiscountRate() float64 {
	if o == nil || IsNil(o.DiscountRate.Get()) {
		var ret float64
		return ret
	}
	return *o.DiscountRate.Get()
}

// GetDiscountRateOk returns a tuple with the DiscountRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeletePrometheusRulesFromOrganizationDto) GetDiscountRateOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscountRate.Get(), o.DiscountRate.IsSet()
}

// HasDiscountRate returns a boolean if a field has been set.
func (o *DeletePrometheusRulesFromOrganizationDto) HasDiscountRate() bool {
	if o != nil && o.DiscountRate.IsSet() {
		return true
	}

	return false
}

// SetDiscountRate gets a reference to the given NullableFloat64 and assigns it to the DiscountRate field.
func (o *DeletePrometheusRulesFromOrganizationDto) SetDiscountRate(v float64) {
	o.DiscountRate.Set(&v)
}
// SetDiscountRateNil sets the value for DiscountRate to be an explicit nil
func (o *DeletePrometheusRulesFromOrganizationDto) SetDiscountRateNil() {
	o.DiscountRate.Set(nil)
}

// UnsetDiscountRate ensures that no value is present for DiscountRate, not even an explicit nil
func (o *DeletePrometheusRulesFromOrganizationDto) UnsetDiscountRate() {
	o.DiscountRate.Unset()
}

// GetIsBound returns the IsBound field value if set, zero value otherwise.
func (o *DeletePrometheusRulesFromOrganizationDto) GetIsBound() bool {
	if o == nil || IsNil(o.IsBound) {
		var ret bool
		return ret
	}
	return *o.IsBound
}

// GetIsBoundOk returns a tuple with the IsBound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePrometheusRulesFromOrganizationDto) GetIsBoundOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBound) {
		return nil, false
	}
	return o.IsBound, true
}

// HasIsBound returns a boolean if a field has been set.
func (o *DeletePrometheusRulesFromOrganizationDto) HasIsBound() bool {
	if o != nil && !IsNil(o.IsBound) {
		return true
	}

	return false
}

// SetIsBound gets a reference to the given bool and assigns it to the IsBound field.
func (o *DeletePrometheusRulesFromOrganizationDto) SetIsBound(v bool) {
	o.IsBound = &v
}

func (o DeletePrometheusRulesFromOrganizationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePrometheusRulesFromOrganizationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.DiscountRate.IsSet() {
		toSerialize["discountRate"] = o.DiscountRate.Get()
	}
	if !IsNil(o.IsBound) {
		toSerialize["isBound"] = o.IsBound
	}
	return toSerialize, nil
}

type NullableDeletePrometheusRulesFromOrganizationDto struct {
	value *DeletePrometheusRulesFromOrganizationDto
	isSet bool
}

func (v NullableDeletePrometheusRulesFromOrganizationDto) Get() *DeletePrometheusRulesFromOrganizationDto {
	return v.value
}

func (v *NullableDeletePrometheusRulesFromOrganizationDto) Set(val *DeletePrometheusRulesFromOrganizationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePrometheusRulesFromOrganizationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePrometheusRulesFromOrganizationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePrometheusRulesFromOrganizationDto(val *DeletePrometheusRulesFromOrganizationDto) *NullableDeletePrometheusRulesFromOrganizationDto {
	return &NullableDeletePrometheusRulesFromOrganizationDto{value: val, isSet: true}
}

func (v NullableDeletePrometheusRulesFromOrganizationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePrometheusRulesFromOrganizationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


