/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the ZadaraRegionListCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZadaraRegionListCommand{}

// ZadaraRegionListCommand struct for ZadaraRegionListCommand
type ZadaraRegionListCommand struct {
	Url *string `json:"url,omitempty"`
	ZadaraAccessKeyId *string `json:"zadaraAccessKeyId,omitempty"`
	ZadaraSecretAccessKey *string `json:"zadaraSecretAccessKey,omitempty"`
}

// NewZadaraRegionListCommand instantiates a new ZadaraRegionListCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZadaraRegionListCommand() *ZadaraRegionListCommand {
	this := ZadaraRegionListCommand{}
	return &this
}

// NewZadaraRegionListCommandWithDefaults instantiates a new ZadaraRegionListCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZadaraRegionListCommandWithDefaults() *ZadaraRegionListCommand {
	this := ZadaraRegionListCommand{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ZadaraRegionListCommand) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZadaraRegionListCommand) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ZadaraRegionListCommand) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ZadaraRegionListCommand) SetUrl(v string) {
	o.Url = &v
}

// GetZadaraAccessKeyId returns the ZadaraAccessKeyId field value if set, zero value otherwise.
func (o *ZadaraRegionListCommand) GetZadaraAccessKeyId() string {
	if o == nil || IsNil(o.ZadaraAccessKeyId) {
		var ret string
		return ret
	}
	return *o.ZadaraAccessKeyId
}

// GetZadaraAccessKeyIdOk returns a tuple with the ZadaraAccessKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZadaraRegionListCommand) GetZadaraAccessKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ZadaraAccessKeyId) {
		return nil, false
	}
	return o.ZadaraAccessKeyId, true
}

// HasZadaraAccessKeyId returns a boolean if a field has been set.
func (o *ZadaraRegionListCommand) HasZadaraAccessKeyId() bool {
	if o != nil && !IsNil(o.ZadaraAccessKeyId) {
		return true
	}

	return false
}

// SetZadaraAccessKeyId gets a reference to the given string and assigns it to the ZadaraAccessKeyId field.
func (o *ZadaraRegionListCommand) SetZadaraAccessKeyId(v string) {
	o.ZadaraAccessKeyId = &v
}

// GetZadaraSecretAccessKey returns the ZadaraSecretAccessKey field value if set, zero value otherwise.
func (o *ZadaraRegionListCommand) GetZadaraSecretAccessKey() string {
	if o == nil || IsNil(o.ZadaraSecretAccessKey) {
		var ret string
		return ret
	}
	return *o.ZadaraSecretAccessKey
}

// GetZadaraSecretAccessKeyOk returns a tuple with the ZadaraSecretAccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZadaraRegionListCommand) GetZadaraSecretAccessKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ZadaraSecretAccessKey) {
		return nil, false
	}
	return o.ZadaraSecretAccessKey, true
}

// HasZadaraSecretAccessKey returns a boolean if a field has been set.
func (o *ZadaraRegionListCommand) HasZadaraSecretAccessKey() bool {
	if o != nil && !IsNil(o.ZadaraSecretAccessKey) {
		return true
	}

	return false
}

// SetZadaraSecretAccessKey gets a reference to the given string and assigns it to the ZadaraSecretAccessKey field.
func (o *ZadaraRegionListCommand) SetZadaraSecretAccessKey(v string) {
	o.ZadaraSecretAccessKey = &v
}

func (o ZadaraRegionListCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZadaraRegionListCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.ZadaraAccessKeyId) {
		toSerialize["zadaraAccessKeyId"] = o.ZadaraAccessKeyId
	}
	if !IsNil(o.ZadaraSecretAccessKey) {
		toSerialize["zadaraSecretAccessKey"] = o.ZadaraSecretAccessKey
	}
	return toSerialize, nil
}

type NullableZadaraRegionListCommand struct {
	value *ZadaraRegionListCommand
	isSet bool
}

func (v NullableZadaraRegionListCommand) Get() *ZadaraRegionListCommand {
	return v.value
}

func (v *NullableZadaraRegionListCommand) Set(val *ZadaraRegionListCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableZadaraRegionListCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableZadaraRegionListCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZadaraRegionListCommand(val *ZadaraRegionListCommand) *NullableZadaraRegionListCommand {
	return &NullableZadaraRegionListCommand{value: val, isSet: true}
}

func (v NullableZadaraRegionListCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZadaraRegionListCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


