/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
	"fmt"
)

// checks if the VsphereList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VsphereList{}

// VsphereList struct for VsphereList
type VsphereList struct {
	Data []VsphereListDto `json:"data"`
	TotalCount int32 `json:"totalCount"`
	AdditionalProperties map[string]interface{}
}

type _VsphereList VsphereList

// NewVsphereList instantiates a new VsphereList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVsphereList(data []VsphereListDto, totalCount int32) *VsphereList {
	this := VsphereList{}
	this.Data = data
	this.TotalCount = totalCount
	return &this
}

// NewVsphereListWithDefaults instantiates a new VsphereList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVsphereListWithDefaults() *VsphereList {
	this := VsphereList{}
	return &this
}

// GetData returns the Data field value
// If the value is explicit nil, the zero value for []VsphereListDto will be returned
func (o *VsphereList) GetData() []VsphereListDto {
	if o == nil {
		var ret []VsphereListDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VsphereList) GetDataOk() ([]VsphereListDto, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *VsphereList) SetData(v []VsphereListDto) {
	o.Data = v
}

// GetTotalCount returns the TotalCount field value
func (o *VsphereList) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *VsphereList) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *VsphereList) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o VsphereList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VsphereList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	toSerialize["totalCount"] = o.TotalCount

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VsphereList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVsphereList := _VsphereList{}

	err = json.Unmarshal(data, &varVsphereList)

	if err != nil {
		return err
	}

	*o = VsphereList(varVsphereList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "totalCount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVsphereList struct {
	value *VsphereList
	isSet bool
}

func (v NullableVsphereList) Get() *VsphereList {
	return v.value
}

func (v *NullableVsphereList) Set(val *VsphereList) {
	v.value = val
	v.isSet = true
}

func (v NullableVsphereList) IsSet() bool {
	return v.isSet
}

func (v *NullableVsphereList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVsphereList(val *VsphereList) *NullableVsphereList {
	return &NullableVsphereList{value: val, isSet: true}
}

func (v NullableVsphereList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVsphereList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


