/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: v1
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
)

// checks if the OrganizationDetailsDtoForAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDetailsDtoForAccount{}

// OrganizationDetailsDtoForAccount struct for OrganizationDetailsDtoForAccount
type OrganizationDetailsDtoForAccount struct {
	Id *int32 `json:"id,omitempty"`
	Name NullableString `json:"name,omitempty"`
	FullName NullableString `json:"fullName,omitempty"`
	CreatedAt NullableString `json:"createdAt,omitempty"`
	Projects []GroupedProjectDto `json:"projects,omitempty"`
	Groups []GroupedOrganizationDto `json:"groups,omitempty"`
	Users []GroupedOrganizationUserDto `json:"users,omitempty"`
}

// NewOrganizationDetailsDtoForAccount instantiates a new OrganizationDetailsDtoForAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDetailsDtoForAccount() *OrganizationDetailsDtoForAccount {
	this := OrganizationDetailsDtoForAccount{}
	return &this
}

// NewOrganizationDetailsDtoForAccountWithDefaults instantiates a new OrganizationDetailsDtoForAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDetailsDtoForAccountWithDefaults() *OrganizationDetailsDtoForAccount {
	this := OrganizationDetailsDtoForAccount{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrganizationDetailsDtoForAccount) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDetailsDtoForAccount) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OrganizationDetailsDtoForAccount) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *OrganizationDetailsDtoForAccount) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *OrganizationDetailsDtoForAccount) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *OrganizationDetailsDtoForAccount) UnsetName() {
	o.Name.Unset()
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *OrganizationDetailsDtoForAccount) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *OrganizationDetailsDtoForAccount) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *OrganizationDetailsDtoForAccount) UnsetFullName() {
	o.FullName.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableString and assigns it to the CreatedAt field.
func (o *OrganizationDetailsDtoForAccount) SetCreatedAt(v string) {
	o.CreatedAt.Set(&v)
}
// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *OrganizationDetailsDtoForAccount) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *OrganizationDetailsDtoForAccount) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetProjects returns the Projects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetProjects() []GroupedProjectDto {
	if o == nil {
		var ret []GroupedProjectDto
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetProjectsOk() ([]GroupedProjectDto, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []GroupedProjectDto and assigns it to the Projects field.
func (o *OrganizationDetailsDtoForAccount) SetProjects(v []GroupedProjectDto) {
	o.Projects = v
}

// GetGroups returns the Groups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetGroups() []GroupedOrganizationDto {
	if o == nil {
		var ret []GroupedOrganizationDto
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetGroupsOk() ([]GroupedOrganizationDto, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []GroupedOrganizationDto and assigns it to the Groups field.
func (o *OrganizationDetailsDtoForAccount) SetGroups(v []GroupedOrganizationDto) {
	o.Groups = v
}

// GetUsers returns the Users field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrganizationDetailsDtoForAccount) GetUsers() []GroupedOrganizationUserDto {
	if o == nil {
		var ret []GroupedOrganizationUserDto
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrganizationDetailsDtoForAccount) GetUsersOk() ([]GroupedOrganizationUserDto, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *OrganizationDetailsDtoForAccount) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []GroupedOrganizationUserDto and assigns it to the Users field.
func (o *OrganizationDetailsDtoForAccount) SetUsers(v []GroupedOrganizationUserDto) {
	o.Users = v
}

func (o OrganizationDetailsDtoForAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDetailsDtoForAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.CreatedAt.IsSet() {
		toSerialize["createdAt"] = o.CreatedAt.Get()
	}
	if o.Projects != nil {
		toSerialize["projects"] = o.Projects
	}
	if o.Groups != nil {
		toSerialize["groups"] = o.Groups
	}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	return toSerialize, nil
}

type NullableOrganizationDetailsDtoForAccount struct {
	value *OrganizationDetailsDtoForAccount
	isSet bool
}

func (v NullableOrganizationDetailsDtoForAccount) Get() *OrganizationDetailsDtoForAccount {
	return v.value
}

func (v *NullableOrganizationDetailsDtoForAccount) Set(val *OrganizationDetailsDtoForAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDetailsDtoForAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDetailsDtoForAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDetailsDtoForAccount(val *OrganizationDetailsDtoForAccount) *NullableOrganizationDetailsDtoForAccount {
	return &NullableOrganizationDetailsDtoForAccount{value: val, isSet: true}
}

func (v NullableOrganizationDetailsDtoForAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDetailsDtoForAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


