/*
Taikun - WebApi

This Api will be responsible for overall data distribution and authorization.

API version: 1.0.0
Contact: noreply@taikun.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package taikuncore

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProxmoxNetworkListDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxmoxNetworkListDto{}

// ProxmoxNetworkListDto struct for ProxmoxNetworkListDto
type ProxmoxNetworkListDto struct {
	Bridge string `json:"bridge"`
	Gateway string `json:"gateway"`
	IpAddress string `json:"ipAddress"`
	NetMask int32 `json:"netMask"`
	BeginAllocationRange string `json:"beginAllocationRange"`
	EndAllocationRange string `json:"endAllocationRange"`
	IsPrivate bool `json:"isPrivate"`
	IsVirtualLbNetwork bool `json:"isVirtualLbNetwork"`
}

type _ProxmoxNetworkListDto ProxmoxNetworkListDto

// NewProxmoxNetworkListDto instantiates a new ProxmoxNetworkListDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxmoxNetworkListDto(bridge string, gateway string, ipAddress string, netMask int32, beginAllocationRange string, endAllocationRange string, isPrivate bool, isVirtualLbNetwork bool) *ProxmoxNetworkListDto {
	this := ProxmoxNetworkListDto{}
	this.Bridge = bridge
	this.Gateway = gateway
	this.IpAddress = ipAddress
	this.NetMask = netMask
	this.BeginAllocationRange = beginAllocationRange
	this.EndAllocationRange = endAllocationRange
	this.IsPrivate = isPrivate
	this.IsVirtualLbNetwork = isVirtualLbNetwork
	return &this
}

// NewProxmoxNetworkListDtoWithDefaults instantiates a new ProxmoxNetworkListDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxmoxNetworkListDtoWithDefaults() *ProxmoxNetworkListDto {
	this := ProxmoxNetworkListDto{}
	return &this
}

// GetBridge returns the Bridge field value
func (o *ProxmoxNetworkListDto) GetBridge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bridge
}

// GetBridgeOk returns a tuple with the Bridge field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetBridgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bridge, true
}

// SetBridge sets field value
func (o *ProxmoxNetworkListDto) SetBridge(v string) {
	o.Bridge = v
}

// GetGateway returns the Gateway field value
func (o *ProxmoxNetworkListDto) GetGateway() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gateway, true
}

// SetGateway sets field value
func (o *ProxmoxNetworkListDto) SetGateway(v string) {
	o.Gateway = v
}

// GetIpAddress returns the IpAddress field value
func (o *ProxmoxNetworkListDto) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *ProxmoxNetworkListDto) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetNetMask returns the NetMask field value
func (o *ProxmoxNetworkListDto) GetNetMask() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetMask
}

// GetNetMaskOk returns a tuple with the NetMask field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetNetMaskOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetMask, true
}

// SetNetMask sets field value
func (o *ProxmoxNetworkListDto) SetNetMask(v int32) {
	o.NetMask = v
}

// GetBeginAllocationRange returns the BeginAllocationRange field value
func (o *ProxmoxNetworkListDto) GetBeginAllocationRange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BeginAllocationRange
}

// GetBeginAllocationRangeOk returns a tuple with the BeginAllocationRange field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetBeginAllocationRangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BeginAllocationRange, true
}

// SetBeginAllocationRange sets field value
func (o *ProxmoxNetworkListDto) SetBeginAllocationRange(v string) {
	o.BeginAllocationRange = v
}

// GetEndAllocationRange returns the EndAllocationRange field value
func (o *ProxmoxNetworkListDto) GetEndAllocationRange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndAllocationRange
}

// GetEndAllocationRangeOk returns a tuple with the EndAllocationRange field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetEndAllocationRangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndAllocationRange, true
}

// SetEndAllocationRange sets field value
func (o *ProxmoxNetworkListDto) SetEndAllocationRange(v string) {
	o.EndAllocationRange = v
}

// GetIsPrivate returns the IsPrivate field value
func (o *ProxmoxNetworkListDto) GetIsPrivate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPrivate
}

// GetIsPrivateOk returns a tuple with the IsPrivate field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetIsPrivateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPrivate, true
}

// SetIsPrivate sets field value
func (o *ProxmoxNetworkListDto) SetIsPrivate(v bool) {
	o.IsPrivate = v
}

// GetIsVirtualLbNetwork returns the IsVirtualLbNetwork field value
func (o *ProxmoxNetworkListDto) GetIsVirtualLbNetwork() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsVirtualLbNetwork
}

// GetIsVirtualLbNetworkOk returns a tuple with the IsVirtualLbNetwork field value
// and a boolean to check if the value has been set.
func (o *ProxmoxNetworkListDto) GetIsVirtualLbNetworkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsVirtualLbNetwork, true
}

// SetIsVirtualLbNetwork sets field value
func (o *ProxmoxNetworkListDto) SetIsVirtualLbNetwork(v bool) {
	o.IsVirtualLbNetwork = v
}

func (o ProxmoxNetworkListDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxmoxNetworkListDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bridge"] = o.Bridge
	toSerialize["gateway"] = o.Gateway
	toSerialize["ipAddress"] = o.IpAddress
	toSerialize["netMask"] = o.NetMask
	toSerialize["beginAllocationRange"] = o.BeginAllocationRange
	toSerialize["endAllocationRange"] = o.EndAllocationRange
	toSerialize["isPrivate"] = o.IsPrivate
	toSerialize["isVirtualLbNetwork"] = o.IsVirtualLbNetwork
	return toSerialize, nil
}

func (o *ProxmoxNetworkListDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bridge",
		"gateway",
		"ipAddress",
		"netMask",
		"beginAllocationRange",
		"endAllocationRange",
		"isPrivate",
		"isVirtualLbNetwork",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProxmoxNetworkListDto := _ProxmoxNetworkListDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProxmoxNetworkListDto)

	if err != nil {
		return err
	}

	*o = ProxmoxNetworkListDto(varProxmoxNetworkListDto)

	return err
}

type NullableProxmoxNetworkListDto struct {
	value *ProxmoxNetworkListDto
	isSet bool
}

func (v NullableProxmoxNetworkListDto) Get() *ProxmoxNetworkListDto {
	return v.value
}

func (v *NullableProxmoxNetworkListDto) Set(val *ProxmoxNetworkListDto) {
	v.value = val
	v.isSet = true
}

func (v NullableProxmoxNetworkListDto) IsSet() bool {
	return v.isSet
}

func (v *NullableProxmoxNetworkListDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxmoxNetworkListDto(val *ProxmoxNetworkListDto) *NullableProxmoxNetworkListDto {
	return &NullableProxmoxNetworkListDto{value: val, isSet: true}
}

func (v NullableProxmoxNetworkListDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxmoxNetworkListDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


