// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/itera-io/taikungoclient/models"
)

// KubernetesDeletePodReader is a Reader for the KubernetesDeletePod structure.
type KubernetesDeletePodReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KubernetesDeletePodReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewKubernetesDeletePodOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewKubernetesDeletePodBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewKubernetesDeletePodUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewKubernetesDeletePodForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewKubernetesDeletePodNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewKubernetesDeletePodInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewKubernetesDeletePodOK creates a KubernetesDeletePodOK with default headers values
func NewKubernetesDeletePodOK() *KubernetesDeletePodOK {
	return &KubernetesDeletePodOK{}
}

/* KubernetesDeletePodOK describes a response with status code 200, with default header values.

Success
*/
type KubernetesDeletePodOK struct {
	Payload models.Unit
}

func (o *KubernetesDeletePodOK) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodOK  %+v", 200, o.Payload)
}
func (o *KubernetesDeletePodOK) GetPayload() models.Unit {
	return o.Payload
}

func (o *KubernetesDeletePodOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKubernetesDeletePodBadRequest creates a KubernetesDeletePodBadRequest with default headers values
func NewKubernetesDeletePodBadRequest() *KubernetesDeletePodBadRequest {
	return &KubernetesDeletePodBadRequest{}
}

/* KubernetesDeletePodBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type KubernetesDeletePodBadRequest struct {
	Payload *models.ValidationProblemDetails
}

func (o *KubernetesDeletePodBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodBadRequest  %+v", 400, o.Payload)
}
func (o *KubernetesDeletePodBadRequest) GetPayload() *models.ValidationProblemDetails {
	return o.Payload
}

func (o *KubernetesDeletePodBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKubernetesDeletePodUnauthorized creates a KubernetesDeletePodUnauthorized with default headers values
func NewKubernetesDeletePodUnauthorized() *KubernetesDeletePodUnauthorized {
	return &KubernetesDeletePodUnauthorized{}
}

/* KubernetesDeletePodUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type KubernetesDeletePodUnauthorized struct {
	Payload *models.ProblemDetails
}

func (o *KubernetesDeletePodUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodUnauthorized  %+v", 401, o.Payload)
}
func (o *KubernetesDeletePodUnauthorized) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *KubernetesDeletePodUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKubernetesDeletePodForbidden creates a KubernetesDeletePodForbidden with default headers values
func NewKubernetesDeletePodForbidden() *KubernetesDeletePodForbidden {
	return &KubernetesDeletePodForbidden{}
}

/* KubernetesDeletePodForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type KubernetesDeletePodForbidden struct {
	Payload *models.ProblemDetails
}

func (o *KubernetesDeletePodForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodForbidden  %+v", 403, o.Payload)
}
func (o *KubernetesDeletePodForbidden) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *KubernetesDeletePodForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKubernetesDeletePodNotFound creates a KubernetesDeletePodNotFound with default headers values
func NewKubernetesDeletePodNotFound() *KubernetesDeletePodNotFound {
	return &KubernetesDeletePodNotFound{}
}

/* KubernetesDeletePodNotFound describes a response with status code 404, with default header values.

Not Found
*/
type KubernetesDeletePodNotFound struct {
	Payload *models.ProblemDetails
}

func (o *KubernetesDeletePodNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodNotFound  %+v", 404, o.Payload)
}
func (o *KubernetesDeletePodNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *KubernetesDeletePodNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKubernetesDeletePodInternalServerError creates a KubernetesDeletePodInternalServerError with default headers values
func NewKubernetesDeletePodInternalServerError() *KubernetesDeletePodInternalServerError {
	return &KubernetesDeletePodInternalServerError{}
}

/* KubernetesDeletePodInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type KubernetesDeletePodInternalServerError struct {
}

func (o *KubernetesDeletePodInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Kubernetes/{projectId}/deletepod/{metadataName}/{podNamespace}][%d] kubernetesDeletePodInternalServerError ", 500)
}

func (o *KubernetesDeletePodInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
