// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewImagesGetSelectedImagesForProjectParams creates a new ImagesGetSelectedImagesForProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImagesGetSelectedImagesForProjectParams() *ImagesGetSelectedImagesForProjectParams {
	return &ImagesGetSelectedImagesForProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImagesGetSelectedImagesForProjectParamsWithTimeout creates a new ImagesGetSelectedImagesForProjectParams object
// with the ability to set a timeout on a request.
func NewImagesGetSelectedImagesForProjectParamsWithTimeout(timeout time.Duration) *ImagesGetSelectedImagesForProjectParams {
	return &ImagesGetSelectedImagesForProjectParams{
		timeout: timeout,
	}
}

// NewImagesGetSelectedImagesForProjectParamsWithContext creates a new ImagesGetSelectedImagesForProjectParams object
// with the ability to set a context for a request.
func NewImagesGetSelectedImagesForProjectParamsWithContext(ctx context.Context) *ImagesGetSelectedImagesForProjectParams {
	return &ImagesGetSelectedImagesForProjectParams{
		Context: ctx,
	}
}

// NewImagesGetSelectedImagesForProjectParamsWithHTTPClient creates a new ImagesGetSelectedImagesForProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewImagesGetSelectedImagesForProjectParamsWithHTTPClient(client *http.Client) *ImagesGetSelectedImagesForProjectParams {
	return &ImagesGetSelectedImagesForProjectParams{
		HTTPClient: client,
	}
}

/* ImagesGetSelectedImagesForProjectParams contains all the parameters to send to the API endpoint
   for the images get selected images for project operation.

   Typically these are written to a http.Request.
*/
type ImagesGetSelectedImagesForProjectParams struct {

	// FilterBy.
	FilterBy *string

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Offset.
	//
	// Format: int32
	Offset *int32

	// OrganizationID.
	//
	// Format: int32
	OrganizationID *int32

	// ProjectID.
	//
	// Format: int32
	ProjectID *int32

	// Search.
	Search *string

	// SortBy.
	SortBy *string

	// SortDirection.
	SortDirection *string

	// V.
	V string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the images get selected images for project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImagesGetSelectedImagesForProjectParams) WithDefaults() *ImagesGetSelectedImagesForProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the images get selected images for project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImagesGetSelectedImagesForProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithTimeout(timeout time.Duration) *ImagesGetSelectedImagesForProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithContext(ctx context.Context) *ImagesGetSelectedImagesForProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithHTTPClient(client *http.Client) *ImagesGetSelectedImagesForProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterBy adds the filterBy to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithFilterBy(filterBy *string) *ImagesGetSelectedImagesForProjectParams {
	o.SetFilterBy(filterBy)
	return o
}

// SetFilterBy adds the filterBy to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetFilterBy(filterBy *string) {
	o.FilterBy = filterBy
}

// WithLimit adds the limit to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithLimit(limit *int32) *ImagesGetSelectedImagesForProjectParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithOffset(offset *int32) *ImagesGetSelectedImagesForProjectParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithOrganizationID(organizationID *int32) *ImagesGetSelectedImagesForProjectParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetOrganizationID(organizationID *int32) {
	o.OrganizationID = organizationID
}

// WithProjectID adds the projectID to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithProjectID(projectID *int32) *ImagesGetSelectedImagesForProjectParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetProjectID(projectID *int32) {
	o.ProjectID = projectID
}

// WithSearch adds the search to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithSearch(search *string) *ImagesGetSelectedImagesForProjectParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetSearch(search *string) {
	o.Search = search
}

// WithSortBy adds the sortBy to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithSortBy(sortBy *string) *ImagesGetSelectedImagesForProjectParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithSortDirection adds the sortDirection to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithSortDirection(sortDirection *string) *ImagesGetSelectedImagesForProjectParams {
	o.SetSortDirection(sortDirection)
	return o
}

// SetSortDirection adds the sortDirection to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetSortDirection(sortDirection *string) {
	o.SortDirection = sortDirection
}

// WithV adds the v to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) WithV(v string) *ImagesGetSelectedImagesForProjectParams {
	o.SetV(v)
	return o
}

// SetV adds the v to the images get selected images for project params
func (o *ImagesGetSelectedImagesForProjectParams) SetV(v string) {
	o.V = v
}

// WriteToRequest writes these params to a swagger request
func (o *ImagesGetSelectedImagesForProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterBy != nil {

		// query param filterBy
		var qrFilterBy string

		if o.FilterBy != nil {
			qrFilterBy = *o.FilterBy
		}
		qFilterBy := qrFilterBy
		if qFilterBy != "" {

			if err := r.SetQueryParam("filterBy", qFilterBy); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationId
		var qrOrganizationID int32

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := swag.FormatInt32(qrOrganizationID)
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationId", qOrganizationID); err != nil {
				return err
			}
		}
	}

	if o.ProjectID != nil {

		// query param projectId
		var qrProjectID int32

		if o.ProjectID != nil {
			qrProjectID = *o.ProjectID
		}
		qProjectID := swag.FormatInt32(qrProjectID)
		if qProjectID != "" {

			if err := r.SetQueryParam("projectId", qProjectID); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}
	}

	if o.SortDirection != nil {

		// query param sortDirection
		var qrSortDirection string

		if o.SortDirection != nil {
			qrSortDirection = *o.SortDirection
		}
		qSortDirection := qrSortDirection
		if qSortDirection != "" {

			if err := r.SetQueryParam("sortDirection", qSortDirection); err != nil {
				return err
			}
		}
	}

	// path param v
	if err := r.SetPathParam("v", o.V); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
