// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/itera-io/taikungoclient/models"
)

// NewProjectsPurgeParams creates a new ProjectsPurgeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProjectsPurgeParams() *ProjectsPurgeParams {
	return &ProjectsPurgeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProjectsPurgeParamsWithTimeout creates a new ProjectsPurgeParams object
// with the ability to set a timeout on a request.
func NewProjectsPurgeParamsWithTimeout(timeout time.Duration) *ProjectsPurgeParams {
	return &ProjectsPurgeParams{
		timeout: timeout,
	}
}

// NewProjectsPurgeParamsWithContext creates a new ProjectsPurgeParams object
// with the ability to set a context for a request.
func NewProjectsPurgeParamsWithContext(ctx context.Context) *ProjectsPurgeParams {
	return &ProjectsPurgeParams{
		Context: ctx,
	}
}

// NewProjectsPurgeParamsWithHTTPClient creates a new ProjectsPurgeParams object
// with the ability to set a custom HTTPClient for a request.
func NewProjectsPurgeParamsWithHTTPClient(client *http.Client) *ProjectsPurgeParams {
	return &ProjectsPurgeParams{
		HTTPClient: client,
	}
}

/*
ProjectsPurgeParams contains all the parameters to send to the API endpoint

	for the projects purge operation.

	Typically these are written to a http.Request.
*/
type ProjectsPurgeParams struct {

	// Body.
	Body *models.PurgeCommand

	// V.
	V string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the projects purge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectsPurgeParams) WithDefaults() *ProjectsPurgeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the projects purge params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProjectsPurgeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the projects purge params
func (o *ProjectsPurgeParams) WithTimeout(timeout time.Duration) *ProjectsPurgeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the projects purge params
func (o *ProjectsPurgeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the projects purge params
func (o *ProjectsPurgeParams) WithContext(ctx context.Context) *ProjectsPurgeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the projects purge params
func (o *ProjectsPurgeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the projects purge params
func (o *ProjectsPurgeParams) WithHTTPClient(client *http.Client) *ProjectsPurgeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the projects purge params
func (o *ProjectsPurgeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the projects purge params
func (o *ProjectsPurgeParams) WithBody(body *models.PurgeCommand) *ProjectsPurgeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the projects purge params
func (o *ProjectsPurgeParams) SetBody(body *models.PurgeCommand) {
	o.Body = body
}

// WithV adds the v to the projects purge params
func (o *ProjectsPurgeParams) WithV(v string) *ProjectsPurgeParams {
	o.SetV(v)
	return o
}

// SetV adds the v to the projects purge params
func (o *ProjectsPurgeParams) SetV(v string) {
	o.V = v
}

// WriteToRequest writes these params to a swagger request
func (o *ProjectsPurgeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param v
	if err := r.SetPathParam("v", o.V); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
