// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CatalogCatalogAppParamsDetailsReader is a Reader for the CatalogCatalogAppParamsDetails structure.
type CatalogCatalogAppParamsDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CatalogCatalogAppParamsDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCatalogCatalogAppParamsDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCatalogCatalogAppParamsDetailsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCatalogCatalogAppParamsDetailsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCatalogCatalogAppParamsDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCatalogCatalogAppParamsDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCatalogCatalogAppParamsDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCatalogCatalogAppParamsDetailsOK creates a CatalogCatalogAppParamsDetailsOK with default headers values
func NewCatalogCatalogAppParamsDetailsOK() *CatalogCatalogAppParamsDetailsOK {
	return &CatalogCatalogAppParamsDetailsOK{}
}

/*
CatalogCatalogAppParamsDetailsOK describes a response with status code 200, with default header values.

Success
*/
type CatalogCatalogAppParamsDetailsOK struct {
	Payload []*CatalogCatalogAppParamsDetailsOKBodyItems0
}

// IsSuccess returns true when this catalog catalog app params details o k response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this catalog catalog app params details o k response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details o k response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this catalog catalog app params details o k response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog catalog app params details o k response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsOK) IsCode(code int) bool {
	return code == 200
}

func (o *CatalogCatalogAppParamsDetailsOK) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsOK  %+v", 200, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsOK) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsOK  %+v", 200, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsOK) GetPayload() []*CatalogCatalogAppParamsDetailsOKBodyItems0 {
	return o.Payload
}

func (o *CatalogCatalogAppParamsDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogCatalogAppParamsDetailsBadRequest creates a CatalogCatalogAppParamsDetailsBadRequest with default headers values
func NewCatalogCatalogAppParamsDetailsBadRequest() *CatalogCatalogAppParamsDetailsBadRequest {
	return &CatalogCatalogAppParamsDetailsBadRequest{}
}

/*
CatalogCatalogAppParamsDetailsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CatalogCatalogAppParamsDetailsBadRequest struct {
	Payload []*CatalogCatalogAppParamsDetailsBadRequestBodyItems0
}

// IsSuccess returns true when this catalog catalog app params details bad request response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this catalog catalog app params details bad request response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details bad request response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this catalog catalog app params details bad request response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog catalog app params details bad request response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *CatalogCatalogAppParamsDetailsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsBadRequest  %+v", 400, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsBadRequest  %+v", 400, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsBadRequest) GetPayload() []*CatalogCatalogAppParamsDetailsBadRequestBodyItems0 {
	return o.Payload
}

func (o *CatalogCatalogAppParamsDetailsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogCatalogAppParamsDetailsUnauthorized creates a CatalogCatalogAppParamsDetailsUnauthorized with default headers values
func NewCatalogCatalogAppParamsDetailsUnauthorized() *CatalogCatalogAppParamsDetailsUnauthorized {
	return &CatalogCatalogAppParamsDetailsUnauthorized{}
}

/*
CatalogCatalogAppParamsDetailsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CatalogCatalogAppParamsDetailsUnauthorized struct {
	Payload *CatalogCatalogAppParamsDetailsUnauthorizedBody
}

// IsSuccess returns true when this catalog catalog app params details unauthorized response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this catalog catalog app params details unauthorized response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details unauthorized response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this catalog catalog app params details unauthorized response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog catalog app params details unauthorized response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *CatalogCatalogAppParamsDetailsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsUnauthorized  %+v", 401, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsUnauthorized  %+v", 401, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsUnauthorized) GetPayload() *CatalogCatalogAppParamsDetailsUnauthorizedBody {
	return o.Payload
}

func (o *CatalogCatalogAppParamsDetailsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CatalogCatalogAppParamsDetailsUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogCatalogAppParamsDetailsForbidden creates a CatalogCatalogAppParamsDetailsForbidden with default headers values
func NewCatalogCatalogAppParamsDetailsForbidden() *CatalogCatalogAppParamsDetailsForbidden {
	return &CatalogCatalogAppParamsDetailsForbidden{}
}

/*
CatalogCatalogAppParamsDetailsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CatalogCatalogAppParamsDetailsForbidden struct {
	Payload *CatalogCatalogAppParamsDetailsForbiddenBody
}

// IsSuccess returns true when this catalog catalog app params details forbidden response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this catalog catalog app params details forbidden response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details forbidden response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this catalog catalog app params details forbidden response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog catalog app params details forbidden response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *CatalogCatalogAppParamsDetailsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsForbidden  %+v", 403, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsForbidden) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsForbidden  %+v", 403, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsForbidden) GetPayload() *CatalogCatalogAppParamsDetailsForbiddenBody {
	return o.Payload
}

func (o *CatalogCatalogAppParamsDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CatalogCatalogAppParamsDetailsForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogCatalogAppParamsDetailsNotFound creates a CatalogCatalogAppParamsDetailsNotFound with default headers values
func NewCatalogCatalogAppParamsDetailsNotFound() *CatalogCatalogAppParamsDetailsNotFound {
	return &CatalogCatalogAppParamsDetailsNotFound{}
}

/*
CatalogCatalogAppParamsDetailsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CatalogCatalogAppParamsDetailsNotFound struct {
	Payload *CatalogCatalogAppParamsDetailsNotFoundBody
}

// IsSuccess returns true when this catalog catalog app params details not found response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this catalog catalog app params details not found response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details not found response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this catalog catalog app params details not found response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this catalog catalog app params details not found response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *CatalogCatalogAppParamsDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsNotFound  %+v", 404, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsNotFound) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsNotFound  %+v", 404, o.Payload)
}

func (o *CatalogCatalogAppParamsDetailsNotFound) GetPayload() *CatalogCatalogAppParamsDetailsNotFoundBody {
	return o.Payload
}

func (o *CatalogCatalogAppParamsDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CatalogCatalogAppParamsDetailsNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCatalogCatalogAppParamsDetailsInternalServerError creates a CatalogCatalogAppParamsDetailsInternalServerError with default headers values
func NewCatalogCatalogAppParamsDetailsInternalServerError() *CatalogCatalogAppParamsDetailsInternalServerError {
	return &CatalogCatalogAppParamsDetailsInternalServerError{}
}

/*
CatalogCatalogAppParamsDetailsInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type CatalogCatalogAppParamsDetailsInternalServerError struct {
}

// IsSuccess returns true when this catalog catalog app params details internal server error response has a 2xx status code
func (o *CatalogCatalogAppParamsDetailsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this catalog catalog app params details internal server error response has a 3xx status code
func (o *CatalogCatalogAppParamsDetailsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this catalog catalog app params details internal server error response has a 4xx status code
func (o *CatalogCatalogAppParamsDetailsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this catalog catalog app params details internal server error response has a 5xx status code
func (o *CatalogCatalogAppParamsDetailsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this catalog catalog app params details internal server error response a status code equal to that given
func (o *CatalogCatalogAppParamsDetailsInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *CatalogCatalogAppParamsDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsInternalServerError ", 500)
}

func (o *CatalogCatalogAppParamsDetailsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v{v}/Catalog/catalog-app-params/{id}][%d] catalogCatalogAppParamsDetailsInternalServerError ", 500)
}

func (o *CatalogCatalogAppParamsDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
CatalogCatalogAppParamsDetailsBadRequestBodyItems0 catalog catalog app params details bad request body items0
swagger:model CatalogCatalogAppParamsDetailsBadRequestBodyItems0
*/
type CatalogCatalogAppParamsDetailsBadRequestBodyItems0 struct {

	// code
	Code string `json:"code,omitempty"`

	// description
	Description string `json:"description,omitempty"`
}

// Validate validates this catalog catalog app params details bad request body items0
func (o *CatalogCatalogAppParamsDetailsBadRequestBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this catalog catalog app params details bad request body items0 based on context it is used
func (o *CatalogCatalogAppParamsDetailsBadRequestBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsBadRequestBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsBadRequestBodyItems0) UnmarshalBinary(b []byte) error {
	var res CatalogCatalogAppParamsDetailsBadRequestBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CatalogCatalogAppParamsDetailsForbiddenBody catalog catalog app params details forbidden body
swagger:model CatalogCatalogAppParamsDetailsForbiddenBody
*/
type CatalogCatalogAppParamsDetailsForbiddenBody struct {

	// detail
	Detail string `json:"detail,omitempty"`

	// instance
	Instance string `json:"instance,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this catalog catalog app params details forbidden body
func (o *CatalogCatalogAppParamsDetailsForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this catalog catalog app params details forbidden body based on context it is used
func (o *CatalogCatalogAppParamsDetailsForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsForbiddenBody) UnmarshalBinary(b []byte) error {
	var res CatalogCatalogAppParamsDetailsForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CatalogCatalogAppParamsDetailsNotFoundBody catalog catalog app params details not found body
swagger:model CatalogCatalogAppParamsDetailsNotFoundBody
*/
type CatalogCatalogAppParamsDetailsNotFoundBody struct {

	// detail
	Detail string `json:"detail,omitempty"`

	// instance
	Instance string `json:"instance,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this catalog catalog app params details not found body
func (o *CatalogCatalogAppParamsDetailsNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this catalog catalog app params details not found body based on context it is used
func (o *CatalogCatalogAppParamsDetailsNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsNotFoundBody) UnmarshalBinary(b []byte) error {
	var res CatalogCatalogAppParamsDetailsNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CatalogCatalogAppParamsDetailsOKBodyItems0 catalog catalog app params details o k body items0
swagger:model CatalogCatalogAppParamsDetailsOKBodyItems0
*/
type CatalogCatalogAppParamsDetailsOKBodyItems0 struct {

	// catalog app name
	CatalogAppName string `json:"catalogAppName,omitempty"`

	// id
	ID int32 `json:"id,omitempty"`

	// is changeable
	IsChangeable bool `json:"isChangeable"`

	// is readonly
	IsReadonly bool `json:"isReadonly"`

	// key
	Key string `json:"key,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this catalog catalog app params details o k body items0
func (o *CatalogCatalogAppParamsDetailsOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this catalog catalog app params details o k body items0 based on context it is used
func (o *CatalogCatalogAppParamsDetailsOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res CatalogCatalogAppParamsDetailsOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CatalogCatalogAppParamsDetailsUnauthorizedBody catalog catalog app params details unauthorized body
swagger:model CatalogCatalogAppParamsDetailsUnauthorizedBody
*/
type CatalogCatalogAppParamsDetailsUnauthorizedBody struct {

	// detail
	Detail string `json:"detail,omitempty"`

	// instance
	Instance string `json:"instance,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this catalog catalog app params details unauthorized body
func (o *CatalogCatalogAppParamsDetailsUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this catalog catalog app params details unauthorized body based on context it is used
func (o *CatalogCatalogAppParamsDetailsUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CatalogCatalogAppParamsDetailsUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res CatalogCatalogAppParamsDetailsUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
