// Code generated by go-swagger; DO NOT EDIT.

package cloud_credentials

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCloudCredentialsForCliParams creates a new CloudCredentialsForCliParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCloudCredentialsForCliParams() *CloudCredentialsForCliParams {
	return &CloudCredentialsForCliParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCloudCredentialsForCliParamsWithTimeout creates a new CloudCredentialsForCliParams object
// with the ability to set a timeout on a request.
func NewCloudCredentialsForCliParamsWithTimeout(timeout time.Duration) *CloudCredentialsForCliParams {
	return &CloudCredentialsForCliParams{
		timeout: timeout,
	}
}

// NewCloudCredentialsForCliParamsWithContext creates a new CloudCredentialsForCliParams object
// with the ability to set a context for a request.
func NewCloudCredentialsForCliParamsWithContext(ctx context.Context) *CloudCredentialsForCliParams {
	return &CloudCredentialsForCliParams{
		Context: ctx,
	}
}

// NewCloudCredentialsForCliParamsWithHTTPClient creates a new CloudCredentialsForCliParams object
// with the ability to set a custom HTTPClient for a request.
func NewCloudCredentialsForCliParamsWithHTTPClient(client *http.Client) *CloudCredentialsForCliParams {
	return &CloudCredentialsForCliParams{
		HTTPClient: client,
	}
}

/* CloudCredentialsForCliParams contains all the parameters to send to the API endpoint
   for the cloud credentials for cli operation.

   Typically these are written to a http.Request.
*/
type CloudCredentialsForCliParams struct {

	// Limit.
	//
	// Format: int32
	Limit *int32

	// Offset.
	//
	// Format: int32
	Offset *int32

	// OrganizationID.
	//
	// Format: int32
	OrganizationID *int32

	// V.
	V string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cloud credentials for cli params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloudCredentialsForCliParams) WithDefaults() *CloudCredentialsForCliParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cloud credentials for cli params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CloudCredentialsForCliParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithTimeout(timeout time.Duration) *CloudCredentialsForCliParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithContext(ctx context.Context) *CloudCredentialsForCliParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithHTTPClient(client *http.Client) *CloudCredentialsForCliParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithLimit(limit *int32) *CloudCredentialsForCliParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithOffset(offset *int32) *CloudCredentialsForCliParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WithOrganizationID adds the organizationID to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithOrganizationID(organizationID *int32) *CloudCredentialsForCliParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetOrganizationID(organizationID *int32) {
	o.OrganizationID = organizationID
}

// WithV adds the v to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) WithV(v string) *CloudCredentialsForCliParams {
	o.SetV(v)
	return o
}

// SetV adds the v to the cloud credentials for cli params
func (o *CloudCredentialsForCliParams) SetV(v string) {
	o.V = v
}

// WriteToRequest writes these params to a swagger request
func (o *CloudCredentialsForCliParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationID != nil {

		// query param organizationId
		var qrOrganizationID int32

		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := swag.FormatInt32(qrOrganizationID)
		if qOrganizationID != "" {

			if err := r.SetQueryParam("organizationId", qOrganizationID); err != nil {
				return err
			}
		}
	}

	// path param v
	if err := r.SetPathParam("v", o.V); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
