// Code generated by go-swagger; DO NOT EDIT.

package opa_profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOpaProfilesDisableGatekeeperParams creates a new OpaProfilesDisableGatekeeperParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOpaProfilesDisableGatekeeperParams() *OpaProfilesDisableGatekeeperParams {
	return &OpaProfilesDisableGatekeeperParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOpaProfilesDisableGatekeeperParamsWithTimeout creates a new OpaProfilesDisableGatekeeperParams object
// with the ability to set a timeout on a request.
func NewOpaProfilesDisableGatekeeperParamsWithTimeout(timeout time.Duration) *OpaProfilesDisableGatekeeperParams {
	return &OpaProfilesDisableGatekeeperParams{
		timeout: timeout,
	}
}

// NewOpaProfilesDisableGatekeeperParamsWithContext creates a new OpaProfilesDisableGatekeeperParams object
// with the ability to set a context for a request.
func NewOpaProfilesDisableGatekeeperParamsWithContext(ctx context.Context) *OpaProfilesDisableGatekeeperParams {
	return &OpaProfilesDisableGatekeeperParams{
		Context: ctx,
	}
}

// NewOpaProfilesDisableGatekeeperParamsWithHTTPClient creates a new OpaProfilesDisableGatekeeperParams object
// with the ability to set a custom HTTPClient for a request.
func NewOpaProfilesDisableGatekeeperParamsWithHTTPClient(client *http.Client) *OpaProfilesDisableGatekeeperParams {
	return &OpaProfilesDisableGatekeeperParams{
		HTTPClient: client,
	}
}

/*
OpaProfilesDisableGatekeeperParams contains all the parameters to send to the API endpoint

	for the opa profiles disable gatekeeper operation.

	Typically these are written to a http.Request.
*/
type OpaProfilesDisableGatekeeperParams struct {

	// Body.
	Body OpaProfilesDisableGatekeeperBody

	// V.
	V string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the opa profiles disable gatekeeper params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OpaProfilesDisableGatekeeperParams) WithDefaults() *OpaProfilesDisableGatekeeperParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the opa profiles disable gatekeeper params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OpaProfilesDisableGatekeeperParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) WithTimeout(timeout time.Duration) *OpaProfilesDisableGatekeeperParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) WithContext(ctx context.Context) *OpaProfilesDisableGatekeeperParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) WithHTTPClient(client *http.Client) *OpaProfilesDisableGatekeeperParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) WithBody(body OpaProfilesDisableGatekeeperBody) *OpaProfilesDisableGatekeeperParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) SetBody(body OpaProfilesDisableGatekeeperBody) {
	o.Body = body
}

// WithV adds the v to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) WithV(v string) *OpaProfilesDisableGatekeeperParams {
	o.SetV(v)
	return o
}

// SetV adds the v to the opa profiles disable gatekeeper params
func (o *OpaProfilesDisableGatekeeperParams) SetV(v string) {
	o.V = v
}

// WriteToRequest writes these params to a swagger request
func (o *OpaProfilesDisableGatekeeperParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param v
	if err := r.SetPathParam("v", o.V); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
