// Code generated by go-swagger; DO NOT EDIT.

package ssh_users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/itera-io/taikungoclient/models"
)

// SSHUsersDeleteReader is a Reader for the SSHUsersDelete structure.
type SSHUsersDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SSHUsersDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSSHUsersDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSSHUsersDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSSHUsersDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSSHUsersDeleteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSSHUsersDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSSHUsersDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSSHUsersDeleteOK creates a SSHUsersDeleteOK with default headers values
func NewSSHUsersDeleteOK() *SSHUsersDeleteOK {
	return &SSHUsersDeleteOK{}
}

/*
SSHUsersDeleteOK describes a response with status code 200, with default header values.

Success
*/
type SSHUsersDeleteOK struct {
	Payload models.Unit
}

// IsSuccess returns true when this ssh users delete o k response has a 2xx status code
func (o *SSHUsersDeleteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ssh users delete o k response has a 3xx status code
func (o *SSHUsersDeleteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete o k response has a 4xx status code
func (o *SSHUsersDeleteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ssh users delete o k response has a 5xx status code
func (o *SSHUsersDeleteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ssh users delete o k response a status code equal to that given
func (o *SSHUsersDeleteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ssh users delete o k response
func (o *SSHUsersDeleteOK) Code() int {
	return 200
}

func (o *SSHUsersDeleteOK) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteOK  %+v", 200, o.Payload)
}

func (o *SSHUsersDeleteOK) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteOK  %+v", 200, o.Payload)
}

func (o *SSHUsersDeleteOK) GetPayload() models.Unit {
	return o.Payload
}

func (o *SSHUsersDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSSHUsersDeleteBadRequest creates a SSHUsersDeleteBadRequest with default headers values
func NewSSHUsersDeleteBadRequest() *SSHUsersDeleteBadRequest {
	return &SSHUsersDeleteBadRequest{}
}

/*
SSHUsersDeleteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type SSHUsersDeleteBadRequest struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this ssh users delete bad request response has a 2xx status code
func (o *SSHUsersDeleteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ssh users delete bad request response has a 3xx status code
func (o *SSHUsersDeleteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete bad request response has a 4xx status code
func (o *SSHUsersDeleteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this ssh users delete bad request response has a 5xx status code
func (o *SSHUsersDeleteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this ssh users delete bad request response a status code equal to that given
func (o *SSHUsersDeleteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the ssh users delete bad request response
func (o *SSHUsersDeleteBadRequest) Code() int {
	return 400
}

func (o *SSHUsersDeleteBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *SSHUsersDeleteBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteBadRequest  %+v", 400, o.Payload)
}

func (o *SSHUsersDeleteBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SSHUsersDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSSHUsersDeleteUnauthorized creates a SSHUsersDeleteUnauthorized with default headers values
func NewSSHUsersDeleteUnauthorized() *SSHUsersDeleteUnauthorized {
	return &SSHUsersDeleteUnauthorized{}
}

/*
SSHUsersDeleteUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type SSHUsersDeleteUnauthorized struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this ssh users delete unauthorized response has a 2xx status code
func (o *SSHUsersDeleteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ssh users delete unauthorized response has a 3xx status code
func (o *SSHUsersDeleteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete unauthorized response has a 4xx status code
func (o *SSHUsersDeleteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this ssh users delete unauthorized response has a 5xx status code
func (o *SSHUsersDeleteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this ssh users delete unauthorized response a status code equal to that given
func (o *SSHUsersDeleteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the ssh users delete unauthorized response
func (o *SSHUsersDeleteUnauthorized) Code() int {
	return 401
}

func (o *SSHUsersDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteUnauthorized  %+v", 401, o.Payload)
}

func (o *SSHUsersDeleteUnauthorized) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteUnauthorized  %+v", 401, o.Payload)
}

func (o *SSHUsersDeleteUnauthorized) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SSHUsersDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSSHUsersDeleteForbidden creates a SSHUsersDeleteForbidden with default headers values
func NewSSHUsersDeleteForbidden() *SSHUsersDeleteForbidden {
	return &SSHUsersDeleteForbidden{}
}

/*
SSHUsersDeleteForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type SSHUsersDeleteForbidden struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this ssh users delete forbidden response has a 2xx status code
func (o *SSHUsersDeleteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ssh users delete forbidden response has a 3xx status code
func (o *SSHUsersDeleteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete forbidden response has a 4xx status code
func (o *SSHUsersDeleteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this ssh users delete forbidden response has a 5xx status code
func (o *SSHUsersDeleteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this ssh users delete forbidden response a status code equal to that given
func (o *SSHUsersDeleteForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the ssh users delete forbidden response
func (o *SSHUsersDeleteForbidden) Code() int {
	return 403
}

func (o *SSHUsersDeleteForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteForbidden  %+v", 403, o.Payload)
}

func (o *SSHUsersDeleteForbidden) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteForbidden  %+v", 403, o.Payload)
}

func (o *SSHUsersDeleteForbidden) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SSHUsersDeleteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSSHUsersDeleteNotFound creates a SSHUsersDeleteNotFound with default headers values
func NewSSHUsersDeleteNotFound() *SSHUsersDeleteNotFound {
	return &SSHUsersDeleteNotFound{}
}

/*
SSHUsersDeleteNotFound describes a response with status code 404, with default header values.

Not Found
*/
type SSHUsersDeleteNotFound struct {
	Payload *models.ProblemDetails
}

// IsSuccess returns true when this ssh users delete not found response has a 2xx status code
func (o *SSHUsersDeleteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ssh users delete not found response has a 3xx status code
func (o *SSHUsersDeleteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete not found response has a 4xx status code
func (o *SSHUsersDeleteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this ssh users delete not found response has a 5xx status code
func (o *SSHUsersDeleteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this ssh users delete not found response a status code equal to that given
func (o *SSHUsersDeleteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the ssh users delete not found response
func (o *SSHUsersDeleteNotFound) Code() int {
	return 404
}

func (o *SSHUsersDeleteNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteNotFound  %+v", 404, o.Payload)
}

func (o *SSHUsersDeleteNotFound) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteNotFound  %+v", 404, o.Payload)
}

func (o *SSHUsersDeleteNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SSHUsersDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSSHUsersDeleteInternalServerError creates a SSHUsersDeleteInternalServerError with default headers values
func NewSSHUsersDeleteInternalServerError() *SSHUsersDeleteInternalServerError {
	return &SSHUsersDeleteInternalServerError{}
}

/*
SSHUsersDeleteInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type SSHUsersDeleteInternalServerError struct {
}

// IsSuccess returns true when this ssh users delete internal server error response has a 2xx status code
func (o *SSHUsersDeleteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this ssh users delete internal server error response has a 3xx status code
func (o *SSHUsersDeleteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ssh users delete internal server error response has a 4xx status code
func (o *SSHUsersDeleteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this ssh users delete internal server error response has a 5xx status code
func (o *SSHUsersDeleteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this ssh users delete internal server error response a status code equal to that given
func (o *SSHUsersDeleteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the ssh users delete internal server error response
func (o *SSHUsersDeleteInternalServerError) Code() int {
	return 500
}

func (o *SSHUsersDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteInternalServerError ", 500)
}

func (o *SSHUsersDeleteInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v{v}/SshUsers/delete][%d] sshUsersDeleteInternalServerError ", 500)
}

func (o *SSHUsersDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
