// Code generated by go-swagger; DO NOT EDIT.

package cron_job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/itera-io/taikungoclient/models"
)

// CronJobFetchOrganizationDetailsReader is a Reader for the CronJobFetchOrganizationDetails structure.
type CronJobFetchOrganizationDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CronJobFetchOrganizationDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCronJobFetchOrganizationDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCronJobFetchOrganizationDetailsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCronJobFetchOrganizationDetailsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCronJobFetchOrganizationDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCronJobFetchOrganizationDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCronJobFetchOrganizationDetailsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCronJobFetchOrganizationDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCronJobFetchOrganizationDetailsOK creates a CronJobFetchOrganizationDetailsOK with default headers values
func NewCronJobFetchOrganizationDetailsOK() *CronJobFetchOrganizationDetailsOK {
	return &CronJobFetchOrganizationDetailsOK{}
}

/* CronJobFetchOrganizationDetailsOK describes a response with status code 200, with default header values.

Success
*/
type CronJobFetchOrganizationDetailsOK struct {
	Payload models.Unit
}

func (o *CronJobFetchOrganizationDetailsOK) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsOK  %+v", 200, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsOK) GetPayload() models.Unit {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsBadRequest creates a CronJobFetchOrganizationDetailsBadRequest with default headers values
func NewCronJobFetchOrganizationDetailsBadRequest() *CronJobFetchOrganizationDetailsBadRequest {
	return &CronJobFetchOrganizationDetailsBadRequest{}
}

/* CronJobFetchOrganizationDetailsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CronJobFetchOrganizationDetailsBadRequest struct {
	Payload *models.ValidationProblemDetails
}

func (o *CronJobFetchOrganizationDetailsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsBadRequest  %+v", 400, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsBadRequest) GetPayload() *models.ValidationProblemDetails {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsUnauthorized creates a CronJobFetchOrganizationDetailsUnauthorized with default headers values
func NewCronJobFetchOrganizationDetailsUnauthorized() *CronJobFetchOrganizationDetailsUnauthorized {
	return &CronJobFetchOrganizationDetailsUnauthorized{}
}

/* CronJobFetchOrganizationDetailsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CronJobFetchOrganizationDetailsUnauthorized struct {
	Payload *models.ProblemDetails
}

func (o *CronJobFetchOrganizationDetailsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsUnauthorized  %+v", 401, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsUnauthorized) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsForbidden creates a CronJobFetchOrganizationDetailsForbidden with default headers values
func NewCronJobFetchOrganizationDetailsForbidden() *CronJobFetchOrganizationDetailsForbidden {
	return &CronJobFetchOrganizationDetailsForbidden{}
}

/* CronJobFetchOrganizationDetailsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CronJobFetchOrganizationDetailsForbidden struct {
	Payload *models.ProblemDetails
}

func (o *CronJobFetchOrganizationDetailsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsForbidden  %+v", 403, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsForbidden) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsNotFound creates a CronJobFetchOrganizationDetailsNotFound with default headers values
func NewCronJobFetchOrganizationDetailsNotFound() *CronJobFetchOrganizationDetailsNotFound {
	return &CronJobFetchOrganizationDetailsNotFound{}
}

/* CronJobFetchOrganizationDetailsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CronJobFetchOrganizationDetailsNotFound struct {
	Payload *models.ProblemDetails
}

func (o *CronJobFetchOrganizationDetailsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsNotFound  %+v", 404, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsTooManyRequests creates a CronJobFetchOrganizationDetailsTooManyRequests with default headers values
func NewCronJobFetchOrganizationDetailsTooManyRequests() *CronJobFetchOrganizationDetailsTooManyRequests {
	return &CronJobFetchOrganizationDetailsTooManyRequests{}
}

/* CronJobFetchOrganizationDetailsTooManyRequests describes a response with status code 429, with default header values.

Client Error
*/
type CronJobFetchOrganizationDetailsTooManyRequests struct {
	Payload *models.ProblemDetails
}

func (o *CronJobFetchOrganizationDetailsTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsTooManyRequests  %+v", 429, o.Payload)
}
func (o *CronJobFetchOrganizationDetailsTooManyRequests) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *CronJobFetchOrganizationDetailsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCronJobFetchOrganizationDetailsInternalServerError creates a CronJobFetchOrganizationDetailsInternalServerError with default headers values
func NewCronJobFetchOrganizationDetailsInternalServerError() *CronJobFetchOrganizationDetailsInternalServerError {
	return &CronJobFetchOrganizationDetailsInternalServerError{}
}

/* CronJobFetchOrganizationDetailsInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type CronJobFetchOrganizationDetailsInternalServerError struct {
}

func (o *CronJobFetchOrganizationDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/CronJob/fetch-organization-details][%d] cronJobFetchOrganizationDetailsInternalServerError ", 500)
}

func (o *CronJobFetchOrganizationDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
