// Code generated by go-swagger; DO NOT EDIT.

package partner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/itera-io/taikungoclient/models"
)

// PartnerBindOrganizationsReader is a Reader for the PartnerBindOrganizations structure.
type PartnerBindOrganizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PartnerBindOrganizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPartnerBindOrganizationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPartnerBindOrganizationsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPartnerBindOrganizationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPartnerBindOrganizationsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPartnerBindOrganizationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPartnerBindOrganizationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPartnerBindOrganizationsOK creates a PartnerBindOrganizationsOK with default headers values
func NewPartnerBindOrganizationsOK() *PartnerBindOrganizationsOK {
	return &PartnerBindOrganizationsOK{}
}

/* PartnerBindOrganizationsOK describes a response with status code 200, with default header values.

Success
*/
type PartnerBindOrganizationsOK struct {
	Payload models.Unit
}

func (o *PartnerBindOrganizationsOK) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsOK  %+v", 200, o.Payload)
}
func (o *PartnerBindOrganizationsOK) GetPayload() models.Unit {
	return o.Payload
}

func (o *PartnerBindOrganizationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerBindOrganizationsBadRequest creates a PartnerBindOrganizationsBadRequest with default headers values
func NewPartnerBindOrganizationsBadRequest() *PartnerBindOrganizationsBadRequest {
	return &PartnerBindOrganizationsBadRequest{}
}

/* PartnerBindOrganizationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PartnerBindOrganizationsBadRequest struct {
	Payload *models.ValidationProblemDetails
}

func (o *PartnerBindOrganizationsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsBadRequest  %+v", 400, o.Payload)
}
func (o *PartnerBindOrganizationsBadRequest) GetPayload() *models.ValidationProblemDetails {
	return o.Payload
}

func (o *PartnerBindOrganizationsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerBindOrganizationsUnauthorized creates a PartnerBindOrganizationsUnauthorized with default headers values
func NewPartnerBindOrganizationsUnauthorized() *PartnerBindOrganizationsUnauthorized {
	return &PartnerBindOrganizationsUnauthorized{}
}

/* PartnerBindOrganizationsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PartnerBindOrganizationsUnauthorized struct {
	Payload *models.ProblemDetails
}

func (o *PartnerBindOrganizationsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsUnauthorized  %+v", 401, o.Payload)
}
func (o *PartnerBindOrganizationsUnauthorized) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *PartnerBindOrganizationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerBindOrganizationsForbidden creates a PartnerBindOrganizationsForbidden with default headers values
func NewPartnerBindOrganizationsForbidden() *PartnerBindOrganizationsForbidden {
	return &PartnerBindOrganizationsForbidden{}
}

/* PartnerBindOrganizationsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PartnerBindOrganizationsForbidden struct {
	Payload *models.ProblemDetails
}

func (o *PartnerBindOrganizationsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsForbidden  %+v", 403, o.Payload)
}
func (o *PartnerBindOrganizationsForbidden) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *PartnerBindOrganizationsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerBindOrganizationsNotFound creates a PartnerBindOrganizationsNotFound with default headers values
func NewPartnerBindOrganizationsNotFound() *PartnerBindOrganizationsNotFound {
	return &PartnerBindOrganizationsNotFound{}
}

/* PartnerBindOrganizationsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PartnerBindOrganizationsNotFound struct {
	Payload *models.ProblemDetails
}

func (o *PartnerBindOrganizationsNotFound) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsNotFound  %+v", 404, o.Payload)
}
func (o *PartnerBindOrganizationsNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *PartnerBindOrganizationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPartnerBindOrganizationsInternalServerError creates a PartnerBindOrganizationsInternalServerError with default headers values
func NewPartnerBindOrganizationsInternalServerError() *PartnerBindOrganizationsInternalServerError {
	return &PartnerBindOrganizationsInternalServerError{}
}

/* PartnerBindOrganizationsInternalServerError describes a response with status code 500, with default header values.

Server Error
*/
type PartnerBindOrganizationsInternalServerError struct {
}

func (o *PartnerBindOrganizationsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v{v}/Partner/bindorganizations][%d] partnerBindOrganizationsInternalServerError ", 500)
}

func (o *PartnerBindOrganizationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
