name: Generate Client

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      force:
        required: false
        type: boolean
        description: 'Force client generation'
        default: false
    secrets:
      url:
        required: true
      showback_url:
        required: true

env:
  GO_VERSION: '1.21'

jobs:
  build:
    name: Generate
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Download swagger-web.json
        run: wget -q "$SWAGGER_URL" -O swagger-web.json
        shell: bash
        env:
          SWAGGER_URL: ${{ secrets.url }}

      - name: Download swagger-showback.json
        run: wget -q "$SHOWBACK_SWAGGER_URL" -O swagger-showback.json
        shell: bash
        env:
          SHOWBACK_SWAGGER_URL: ${{ secrets.showback_url }}

      - name: Should regenerate client
        id: check
        shell: bash
        run: |
          [[ ${{ inputs.force }} = true ]] || ./.github/should_regenerate_client.sh
        continue-on-error: true

      - name: Setup Git
        if: steps.check.outcome == 'success'
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Go
        if: steps.check.outcome == 'success'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download newest OpenAPI generator
        if: steps.check.outcome == 'success'
        # Adapted form bash launcher script at https://openapi-generator.tech/docs/installation
        run: |
          function latest.tag {
            local uri="https://api.github.com/repos/${1}/releases"
            local ver=$(curl -s ${uri} | jq -r 'first(.[]|select(.prerelease==false)).tag_name')
            if [[ $ver == v* ]]; then
            ver=${ver:1}
            fi
            echo $ver
          }
          ghrepo=openapitools/openapi-generator
          artifactid=openapi-generator-cli
          ver=${OPENAPI_GENERATOR_VERSION:-$(latest.tag $ghrepo)}
          jar=${artifactid}-${ver}.jar 
          wget -q "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/$ver/$jar" -O openapi-generator-cli.jar

      - name: Set up Java
        if: steps.check.outcome == 'success'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Generate Client
        if: steps.check.outcome == 'success'
        run: ./.github/generate_client.sh
        shell: bash

      - name: Delete swagger-web.json
        if: steps.check.outcome == 'success'
        run: rm swagger-web.json
        shell: bash

      - name: Delete swagger-showback.json
        if: steps.check.outcome == 'success'
        run: rm swagger-showback.json
        shell: bash

      - name: Delete openapi-generator
        if: steps.check.outcome == 'success'
        run: rm openapi-generator-cli.jar
        shell: bash

      - name: Commit
        if: steps.check.outcome == 'success'
        shell: bash
        run: |
          git add .
          git commit -m "feat: update generated client"

      - name: Push
        if: steps.check.outcome == 'success'
        shell: bash
        run: git push
