// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdminUsersResponseData admin users response data
//
// swagger:model AdminUsersResponseData
type AdminUsersResponseData struct {

	// csm
	Csm bool `json:"csm"`

	// email
	Email string `json:"email,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// organization name
	OrganizationName string `json:"organizationName,omitempty"`

	// owner
	Owner bool `json:"owner"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this admin users response data
func (m *AdminUsersResponseData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this admin users response data based on context it is used
func (m *AdminUsersResponseData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdminUsersResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdminUsersResponseData) UnmarshalBinary(b []byte) error {
	var res AdminUsersResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
