// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NotificationListDto notification list dto
//
// swagger:model NotificationListDto
type NotificationListDto struct {

	// action message
	ActionMessage string `json:"actionMessage,omitempty"`

	// action status
	ActionStatus string `json:"actionStatus,omitempty"`

	// category
	Category string `json:"category,omitempty"`

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// is deleted
	IsDeleted bool `json:"isDeleted"`

	// project Id
	ProjectID int32 `json:"projectId,omitempty"`

	// project name
	ProjectName string `json:"projectName,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this notification list dto
func (m *NotificationListDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notification list dto based on context it is used
func (m *NotificationListDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NotificationListDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationListDto) UnmarshalBinary(b []byte) error {
	var res NotificationListDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
