// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OpenstackQuotasCommand openstack quotas command
//
// swagger:model OpenstackQuotasCommand
type OpenstackQuotasCommand struct {

	// id
	ID int32 `json:"id,omitempty"`
}

// Validate validates this openstack quotas command
func (m *OpenstackQuotasCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this openstack quotas command based on context it is used
func (m *OpenstackQuotasCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OpenstackQuotasCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OpenstackQuotasCommand) UnmarshalBinary(b []byte) error {
	var res OpenstackQuotasCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
