// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RebootServerCommand reboot server command
//
// swagger:model RebootServerCommand
type RebootServerCommand struct {

	// server Id
	ServerID int32 `json:"serverId,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this reboot server command
func (m *RebootServerCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this reboot server command based on context it is used
func (m *RebootServerCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RebootServerCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RebootServerCommand) UnmarshalBinary(b []byte) error {
	var res RebootServerCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
