// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TanzuStorageListCommand tanzu storage list command
//
// swagger:model TanzuStorageListCommand
type TanzuStorageListCommand struct {

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// port
	Port int32 `json:"port,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this tanzu storage list command
func (m *TanzuStorageListCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tanzu storage list command based on context it is used
func (m *TanzuStorageListCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TanzuStorageListCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TanzuStorageListCommand) UnmarshalBinary(b []byte) error {
	var res TanzuStorageListCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
